modules:
  - "pdfium"
  - "trace_event_common"
  - "chromium_build"
urls:
  pdfium:
    extract_path: ""
    url_format: "https://pdfium.googlesource.com/pdfium/+archive/{branch}.tar.gz"
    git_url: "https://pdfium.googlesource.com/pdfium"
  trace_event_common:
    extract_path: "base/trace_event/common"
    url_format: "https://chromium.googlesource.com/chromium/src/base/trace_event/common/+archive/{branch}.tar.gz"
    git_url: "https://chromium.googlesource.com/chromium/src/base/trace_event/common"
  chromium_build:
    extract_path: "build"
    url_format: "https://chromium.googlesource.com/chromium/src/build/+archive/{branch}.tar.gz"
    git_url: "https://chromium.googlesource.com/chromium/src/build"
branches:
  current:
    pdfium: "d8ce1653bc79f8fda26d637aa88ea295a1a05e4b"
    trace_event_common: "68d816952258c9d817bba656ee2664b35507f01b"
    chromium_build: "2278900a4482055b503476461118ae0f818a9a40"
  master:
    pdfium: "main"
    trace_event_common: "main"
    chromium_build: "main"
