name: Android
on:
  pull_request:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  calculate-matrix:
    runs-on: 'ubuntu-latest'
    outputs:
      matrix: ${{ steps.calc-build-matrix.outputs.matrix }}
    steps:
      - name: 'Calculate build matrix'
        id: 'calc-build-matrix'
        shell: python
        run: |
          import itertools
          import json
          import pprint
          branch_list = ["current"]
          if "${{ github.event_name }}" != "release":
            branch_list.append("master")
          android_abi_list = ["x86_64", "arm64-v8a"]
          api_level_list = [21]
          matrix = [{"branch": branch, "android-abi": android_abi, "api-level": api_level} for branch, android_abi, api_level in itertools.product(branch_list, android_abi_list, api_level_list)]
          pprint.pprint(matrix)
          print("::set-output name=matrix::{}".format(json.dumps(matrix)))
  build-cmake:
    needs: 'calculate-matrix'
    strategy:
      matrix:
        include: ${{ fromJSON(needs.calculate-matrix.outputs.matrix) }}
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'Install python dependencies'
        run: |
          python -m pip install -r requirements.txt
      - name: 'Download pdfium sources'
        run: |
          python pdfium_download.py --branch "${{ matrix.branch }}" --destination "pdfium"
      - name: 'Configure, build and install static pdfium'
        run: |
          cmake -S cmake -B build_static \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.android-abi }} \
            -DANDROID_NATIVE_API_LEVEL=${{ matrix.api-level }} \
            -DPDFIUM_ROOT="${{ github.workspace }}/pdfium" \
            -DCMAKE_INSTALL_PREFIX=staticprefix \
            -DBUILD_SHARED_LIBS=OFF
          cmake --build build_static --parallel
          cmake --build build_static --target install
      - name: 'Configure, build and install shared pdfium'
        run: |
          cmake -S cmake -B build_static \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.android-abi }} \
            -DANDROID_NATIVE_API_LEVEL=${{ matrix.api-level }} \
            -DPDFIUM_ROOT="${{ github.workspace }}/pdfium" \
            -DCMAKE_INSTALL_PREFIX=sharedprefix \
            -DBUILD_SHARED_LIBS=ON
          cmake --build build_shared --parallel
          cmake --build build_shared --target install
